const fs = require('fs');
class StringArray {
    constructor(){ 
    }
    
    getQuote() {
       return ["TO LIVE IS TO DIE AND IF THAT IS THE SOLE TRUTH AT LEAST MAKE IT REALLY, REALLY FUNNY \n — EpicRaisin, GM27 Phase 1", "If I was boring I probably wouldn’t be sitting in a therapy office rn :3 \n — Lynmato, GM27 Premiere", "i might have schemed too hard \n — Formica, GM27 Phase 2",
        "That doesn't sound... Enticing \n — Jeff, GM27 Phase 3", "Goodbye Wettin Mine \n — Arne, GM27 Finale",
        "He's gonna be a real threat later on :D \n — Uhstraalis, GM25 Premiere", "You know... I almost feel sorry for them. \n — Voyager, GM25 Phase 1", "I’m surrounded by idiots and the smartest among them is fucking Briswall \n — Seclyria, GM25 Phase 2", "Wait, I can vote? \n — Clementine, GM25 Phase x",
        "God, do I fucking love money! \n — Felinia, GM25 Phase 3", "It's just like the high school ball all over again \n — Uhstraalis, GM25 Phase 4", "Your honor, can you bench 315? \n — Seclyria, GM25 Finale",
        "God I want to punch someone in the jaw \n — Dom, GM26 Day 1", "I am creating a bipolar political landscape \n — Drayde, GM26 Day 2", "It's like Ubisoft releasing their games \n — Pelu, GM26 Day 3", "I'm so close to winning big \n — Renaissance, GM24 Premiere",
        "“Who said I had a game plan? \n — James, GM24 Phase 1", "“Death P.A.C.T. type shit. \n — Carbon, GM24 Phase 2", "He has been my mortal enemy this whole game \n — Pixelball, GM24 Phase 3", "Just broke up with my gf, need to focus entirely on Grand Mapper \n — Dimanyan, GM24 Phase 4", "WE FORGOT THE PHASE QUOTE \n — Siib, GM24 Finale",
        "I’m a genius is what I've discovered today \n — Charlotte, GM23 Premiere", "Natural Selection \n —  Mitadare, GM23 Phase 1", "Why are Romanians so suicidal \n — Drayde, GM23 Phase 2", "It’s the endgame, for me at least \n — Drayde. GM23 Phase 3",
        "I Never Thought He'd Go That Far... \n — Voyager, GM23 Phase 4", "I am from Shehui what do you expect \n — Lynmato, GM23 Finale", "ok the meds wore off \n — Kamepin UA, GM20", "i feel like everyone in my union lacks brain cells \n — Great British, GM22 Premiere",
        "i was in the railing process \n — Mitadare, GM22 Phase 1", "Can I just say this whole game I’ve been acting more paranoid than Stalin himself \n — Etherian, GM22 Phase 2",
        "i'm gonna have to clear my search history \n — Uhstraalis, GM22 Phase 3", "duat never dies \n — Rlcchamp, GM22 Phase 4", "WATCH ME get second place \n — Etherian, GM22 Finale",
        "Get your shoebill bird music ready. \n — Nuuknein, GM21 Premiere", "Halfway through the countdown and shit has already hit the fan \n — DomIsBored, GM21 Episode 2", "This team actually fucking sucks holy shit \n — Magical Noob, GM21 Episode 3",
        "oohhhh please lady luck bless me with fortune here \n — Interflux, GM21 Episode 4", "Can I count on your vote? \n — Evelyn, GM21 Episode 5",
        "Please \n — Nuuknein, GM21 Episode 6", "Bring on the chariot, motherfuckers. \n — Interflux, GM21 Episode 7", "I need Arrovania back in the game. \n — Gulfstream, GM21 Episode 8",
        "THE AGENDAAAAAAAAA \n — Interflux, GM21 Finale", "I KNOW THE PRODUCERS ARE IN ON IT, OBVIOUSLY GREENBALL IS IN ON IT, PROBABLY RUSSIAN SPY, AND THE CIA. \n — Holy Sealandic, GM17 Premiere", "he left me on read 😬 \n — Russian Spy, GM17 Episode 2",
        "skyrim dialogue \n — Jordi, GM17 Episode 3", "Caduceus you've gained more followers since your arrival to my house hold... \n — Cornelius, GM17 Episode 4",
        "i fear that this may be a clash of the alliance \n — Mexican, GM17 Episode 5", "i call it a highway rescue mission \n — Minkes, GM17 Episode 6", "Trent should have checked the weather \n — Fresco, GM17 Episode 7",
        "sexy fresco ssc 4th place medal... 🤙 \n — Duck, GM17 Episode 8", "AS A ROACH I WOULD LIKE TO GIVE HIM THE RAT AWARD \n — Cornelius, GM17 Episode 9", "All our allies had gone to Revenge \n And my friends were alongside \n With our hearts, we held the key \n — Cheri, GM17 Finale",
        "It won’t replace the lack of parental love you receive \n — Seclyria, GM28 Premiere",
        "MY ALLIES ARE RETARDS AND MY ENEMIES ARE RETARDS WITH GRUDGES \n — Olympus, GM28 Phase 1", "You can kill the chart man, but never the charts \n — Eoem, GM28 Phase 2", "its time for battle of mid to commence \n — Bumble, GM28 Phase 3",
        "Time to rig the votes! \n — Acadia, GM28 Phase 4", "I am Grand Mapper's Hillary Clinton! \n — Acadia, GM28 Finale", "I barely survived. \n — Briswall, GM18 Phase 1",
        "What’s happening \n — Sundslime, GM18 Phase 2", "Let the real game begin. \n — Meme, GM18 Phase 3",
        "all according to plan \n — Swiss, GM18 Phase 4", "I MADE IT \n — Swiss, GM18 Finale",
        "Italian, Sicilian, you’re both gonna submit or I’m gonna remove your balls \n — Darth Iron American, GM19 Premiere", "we need to end the two party system \n — Rah, GM19 Phase 1",
        "Theres nothing we can do \n — Italian, GM19 Phase 2 \n https://cdn.discordapp.com/attachments/1164996869978603672/1169736657336012913/caption.png?", "I did not barely survive. \n — Polnoc, GM19 Phase 3", "One last, Puhiover... \n — Polnoc \n and its inoback. \n — Arux, GM19 Finale",
        "No i will not pay for my sins \n — Chibury, GM3B Premiere", "can you betray people in grand mapper \n — Fabby Flab, GM3B Prelude", "this begins my hunger strike \n — Siib, GM3B Merge", "Trust in the Kameplan \n — Kamepin, GM3B Finale",
        "Grand Mapper 1B is like, lost media to us. \n — Rlcc \n NO GM1B PHASE QUOTES :( \n except for...\n UNCLE GRANDPA!!\n — Greenball, GM1B ", "MWAHAHAH NO PHASE QUOTE FOR YOU!! 😈 <:Winner_Doom:1292555223008809023>",
        "MWAHAHAH THE AMAZING GRINCH VENANT WILL GIVE YOU NO PHASE QUOTE!! UNMERRY CHRISTMAS TO YOU!! 😈 <:Winner_Venant:1292555279719858178>", "I snuggle up to the prods to rig the game in my favor \n — Tetno, GM4B Premiere",
        "My manipulation tactics might work this time...\n — Axel, GM4B Phase 1", "I love lacking sanity \n — Chidbury, GM4B Phase 2", "I voted *** — Freshball, GM4B Finale",
        "I CAN ONLY CRASH OUT \n — Olympus, GM29 Premiere", "ON EVERYONE'S SOULS I AM MAKING IT TO MERGE \n — Evelyn, GM29 Phase 1", "The dog bit back and now he has rabies. He's on borrowed time now. \n — Sund, GM29 Phase 2",
        "id work on this more but i developed a degree of second hand embarrassment when i realized i was making mapper yaoi \n — Olympus, GM29 Phase 3", "You either die a threat, or you live long enough to see yourself become a floater. \n — Eoem, GM29 Phase 4",
        "im back in action as a chaos agent \n — Olympus, GM29 Phase 5", "...my brain is so not working \n — Slaya, GM29 Finale", "my physical body still quivers \n — Voyager, GM5B Premiere", "hell i didnt even know aztecs were a thing till this season \n — Sovil, GM5B Unosun",
        "I need to pull a woman \n — Greenball, GM5B Duosun", "Call me mental on the dance floor the way I break down \n — Seclyria, GM5B Triosun", "The walking corpse will be dead when I say so \n — Faboomko, GM5B Quadrosun", "Idk kill me \n — Foxlandia, GM5B Ultisun",
        "I watch from the heavens too, they call me a god \n — Greenball, GM5B Finale", "But as I have come to know in my previous GM runs, logic is a particularly scarce ressource among contestants \n — Nuuknein, GM30 Premiere", "Ive QUIT my job \n — Dimanyan, GM30 Phase 1",
        "I had plans, I just... I just couldn’t commit to them \n — Capital, GM30 Phase 2", "Nope, I stared death in the eye, and it blinked \n — Arne, GM30 Phase 3", "These lessons will be something I will remember for decades to come \n — American, GM30 Finale",
        "The moment anyone shows their heart to me is the moment it’s skewered straight down the middle \n — Seclyria, GM31 Premiere", "I have clearly made a mistake in assuming that my opponents are intelligent \n — New Abyssinia, GM31 Phase 1",
        "Not funny when my team is four gay men, and the opposition is also gay. Fuck it gay mapper idk \n — Kites, GM31 Phase 2", "Like thanks for caring about my health mom but I really need to do this grand mapper sub \n — Narvon, GM31 Phase 3",
        "I became the very thing I said I hated at the beginning \n — Narvon, GM31 Finale", "We live in a Fool Time world \n — Meme, GM32 Premiere", "plss siib I need ts:sob::sob::sob::sob:my union kinda homeless \n — Sovil, GM32 Phase 1",
        "This party bows to this populist \n — Uhstraalis, GM32 Phase 2", "I am the rookie slayer \n — Meme, GM32 Phase 3", "Going to channel my inner Lazer Kiwi. \n — Linearis, GM32 Finale", "We gotta purge the weak to become strong \n — Alumery, GM33 Premiere", "If nobody from Argaeus is weak enough I might have to settle for somebody better than me and betray them afterwards.\n — Ermine, GM33 Phase 1", "I've been crying, screaming, and throwing up over the last hour \n — Sigerian, GM33 Phase 2", "This is genuinely like a jv athlete racing Usain Bolt :sob::sob: \n — Staking, GM33 Phase 3",  "From when i first been here, i treated people as pawn, something that can lead to me victory of greatness. Yet here I'am treating people as allies, as something worthy, and as people. \n — Hikaruz, GM33 Finale", "Benevolence and altruism are not in my vocabulary \n — Archipel, GM34 Premiere","I quit on my own terms, not someone else's. \n — Ar55, GM34 Phase 1", "I crave to become chaos itself \n — Hexor, GM34 Phase 2", "If You're Reading This, I am Dead \n — Geography Teacher, GM34 Phase 3", "GIVE ME THREE IDOLS NETANYAHU \n — Phil, GM34 Phase 4", "Having what it takes isn't the most important, its whether taking what it takes to win it all. \n — Adata, GM34 Finale"];
    }
    
   	getGreenQuote(){
     return ["Flash memory can be used to store data and bss sections! Did you know that the heap is what is used for dynamic memory allocation during program execution?Currently, I am getting completely FUCKED with midterms. Life advice for teachers, please remember to assign tests a bit before midterm grades are due, I know your lazy asses all do the same bullshit and wait to give tests at the same exact time in the middle of the semester. \n I Am going to be touched inappropiately by my Digital Systems teacher tomorrow.",
        "Sometimes, the stupidest guy in the room could be smart. If someone asks an obvious question, they could very well be overthinking the situation and thinking of scenarios far beyond your comprehension.",
        "95% of the time you act confident and know what the fuck you’re doing, you can get away with practically anything. Generally, the other 5% of scenarios can be covered with tactful planning. Look like a hustler, have a plan, and people will generally not question you unless it’s out of the ordinary. Granted, I know none of yall will listen because you guys are gonna get scared doing it.", "Midterms are far worse than finals.", "Don’t fail your midterms.",
        "Do not gamble fake money during a financial literacy lecture and have all your friends laugh as they stare at your screen thinking its real. You will get bitched out by the professor and probably watch your participation grade go down if hes a spiteful guy. \n ... i love plinko...\n Also I’m 98% sure this guy is gonna try to rig my participation grade over this one incident", "Running between the hours of 1-4am is extremely fun! No idea if it’s actually healthy tho.", "One must celebrate Mario Day in some capacity. Happy MAR10 folks :)", "One of the most humbling experiences is watching a blind person ski far better than you while out on the slopes. I thought I was getting good ☹️",
        "If you see a friendly female acquaintance who is wearing a nice outfit on the plane while going back to your university (after having a near death plane accident) and she waves at you, and when she comes up to your seat she proceeds to give you a high five, and she pats you on the head bc you’re sitting and she’s standing…\n \n \n \n \n \n you might learn something new about yourself.",
        "Life would genuinely be so much better if I was just some shitty isekai protagonist. \n The closest thing you and I will ever get to this dream is by simply playing and doing well in Grand Mapper. You have heroes, villains, and it’s a genuine escape from reality. It’s a quest for glory, where you have many obstacles in your way. The social dynamics especially make it special. Almost every Grand Mapper experience I’ve had has been action packed and I genuinely think I am the main character. \n Apply to Grand Mapper to start your own quest https://discord.com/channels/1131317607539167234/1133167143249268827",
        "When there’s an lockdown drill in middle school, DON’T be in the bathroom. First off ts is scary because you’re confused and in a small space. Also, if you’re in the bathroom, DO NOT, I repeat, DO NOT be mid shit. You will follow the protocol and lock yourself in the stall and be stuck in an uncomfortable squatting position on the toilet for 40 min. Due to this, you will get red and sweaty, I repeat, red and sweaty. You will eventually realize the drill is over and walk back to your class, and since you basically did a 40 min squat workout, it looks like you were going thru shit. The popular girl will spread shit that you were crying, which is bad news in 8th grade, especially when this girl is best friends with your crush. \n Basically, don’t use the bathroom during school in case of this highly specific incident.", "If you go to bed consistently before 12 you’re a bitch 🍼", "If you don’t have a car, I don’t recommend using the Taco Bell drive through, especially if you are wearing a silly military uniform. You will get laughed at by white girls.",
        "Most things in life are frankly just a glorified popularity contest. Case closed. \n Also, extra bit of advice \n Always carry a nail clipper with you \n You never know when you’ll need it",
        "If your life isn’t either a continuous “Black Hole Sun” edit, or “Dreams and Nightmares” edit, genuinely what are you doing?", "You can literally be 6'3 but most girls will still somehow end up falling in love with some fucker who's literally built like Toad from Mario. \n side note: these dudes are also the trashiest mfs on the planet",
        "Struggling to sleep? Here’s a tip! Watch random Undertale iceberg videos. I don’t know why but I’m in another Undertale phase… but hey at least the vids help me 😴",
        "If you ever loan your switch to someone, DO NOT let them find you have Doki Doki Literature Club installed on it. They WILL think you’re a hentai addict, and they WON’T understand that you got it for shits and gigs bc it’s a peak game. Your chances of being socially accepted WILL go down, as they play on your switch as you finish 2 assignments you procrastinated throughout the week!",
        "So let’s say, hypothetically, you develop feelings for a girl. Let’s say you tell your girl best friend about it. Now, let’s say you tell this aforementioned girl best friend (@Madison) this news and then the girl it’s about coincidentally sees the text message and crashes out on you. You write an Oscar-level response to her crash out (idk why she was mad) and then she says she’ll give you a chance, and you have no idea how you felt about it. And then, hypothetically, you accept because why not, not knowing she was drunk. And then, hypothetically, she embarrassingly tells your friend she didn’t mean it, which kinda sucks. \n \n Basically, people are stupid when they’re drunk, and this is another reason why I’m heavily against drinking! :D",
        "The best way to revive friendships is iMessage games, specifically Word Hunt and Basketball. That’s why none of my friends have androids. \n https://cdn.discordapp.com/attachments/1344527076618928190/1361079481095290920/IMG_1079.png?ex=6800bf4b&is=67ff6dcb&hm=9e1fc23b2dbc13fd57d322619b299cea968085433f023e14c71bff14fdefd0e8&",
        "The worst thing that has happened to the American food industry is the great schism between breakfast options and lunch/dinner options. Why the FUCK am I at a Chic Fil A at an airport and the only shit they have is a piece of breaded chicken on a fucking dry ass biscuit. I also hate croissants. Like we should just bring back all day breakfast. If I want McDonalds Hotcakes (pancakes) at 7PM, I want them shits at 7PM. Don’t give me any bullshit about “muh duh breakfast ended at 11am.” Jeez just mash your two mid ass menus together ain’t that deep.",
        "Exam period is the BEST time to cut weight. I’ve been tryna cut for a minute and I’ve lost hella weight recently. Hopefully I can keep it up after I finish everything", "Dude live music at restaurants is beyond ass. Like bro there’s nothing I hate more than walking into a restaurant with family or friends when the music is fucking blaring, especially when it’s some random shithead playing mid ass music live. It’s so loud to the point where I can’t hear shit 3 feet away from me. Ordering becomes a nightmare, talking becomes a nightmare, and there’s no way to tune it out if the music is mid. Also, if they take requests, you already know they’re not gonna know the song you suggest (I know from personal experience). I get why restaurants do it, they bring in crowds of people who love mid music and want to be deaf after enjoying their meals, but holy shit please if anyone here runs a restaurant never do this.",
        "Whatever you do, avoid the Baby Einstein community with a 39 and a half foot pole, please. There are some very... interesting characters involved over there. Some of them are absolute chillers, but most are a little too... excited and passionate about this wonderful DVD series made by Julie Aigner-Clarke. Listen, I love Baby Einstein just as much as the next guy, but holy shit bro. At least they buy cool memorbilia and the puppets, those are actually pretty cool, and learning more about where everything came from was nice. But yeah,  theres a lot of toxicity brewing over there, lots of beef, questionable relationships, questionable amount of shipping. \n\nAlso, I am not the only person from Grand Mapper to venture out to that side of the community. The other two members are none other than... Kirbytron and Reii/Kitz/Astrid/Diddy/Not Felinia/idfk anymore, our favorite lovebirds. \n\nBut yeah, lesson learned kids, dont venture too deep into those woods... Don't go over the garden wall.", "watch uhhstraalis",
        "Want to make easy money? Go to a family Memorial Day Weekend party with a bored ass 8 year old hustling for cash by fetching drinks for random adults for one dollar each. Talk to the kid, and notice he’s made $120 dollars. Since he cannot survive without a screen for more than 2 hours, he then begins to beg you to use your phone for 10 min for 10 bucks…\n\nEasy money. I love teaching America’s youth business transactions! We now have a secret “Bombodilo Crocodilo” handshake and I’ve taught him many pointers from a great piece of literature “GreenBall’s Nasty Tricks.” The future of our country 🇺🇸🫡", "If you have a friend that goes through your phone when you’re not around and accidentally keeps it unlocked, and uses your message history with a close and trusted friend to attack that person, don’t have that person in your life! \nSome psycho went thru womanball’s message history w me and began drunkenly attacking me over me simply explaining the truth after she did something beyond fucked up to me 💀",
        "Tetno is actually mad cool guys. He stands at an impressively tall stature for a man of Chinese descent. Might ask for his autograph lowk he won 4B :flushed::biting_lip:", "White people can rap too! If they can do it, you can achieve your dreams no matter who you are!",
        "This bit of life advice is something that I actually hope y’all consider taking it. A little more like a #lousiana-fireside-chats\n\nI was on a 5 mile run a couple days ago, and I pass by my Grandma’s house. My grandma died in November 2023, about a week before I came home for Thanksgiving from my first semester at military college. I celebrated my 18th birthday the week before I left Long Island in August 2023, and I had seen my Grandma a week before. She asked me to come visit one time before I went to college. I wanted to, but I got caught up in other grad parties, my own massive bday/grad function (which she rainchecked), and ~~making out w a goth girl I was in a situationship with~~ saying goodbye to friends. I realized this when I was heading down to school, and I regretted it, but thought I’d see her first thing Thanksgiving. But a week before, my mom called me, and delivered the news. My regret was (and still is) immeasurable.\n\nSo my message is, treat everyone, especially the people that matter to you most, like it’s the last time you’ll see them. I don’t take this advice well, but I hope yall do and know that life is unpredictable. Not to scare yall but shit can and will happen. I lost one of my friends at the end of 2024 unexpectedly when he suffered a heart attack while at the gym. Even today, my buddy just lost his grandma.\n\nI had this message typed out the night of the 5 mile run, but I forgot to send it. But please guys actually listen to me here. \n\n*TL;DR Treat everyone like it’s the last time you’ll see them. You’ll mess up, yeah, but just try your best especially with those who may be older in your real life*",
        "1. Never sit for 8 hours ranking balls with 20 other degen virgins screaming at the you\n\n2. Flavored water is ass never getting an air sip of Tetno‘s water again", "Wear sunscreen.\nI have a massive sunburn rn and it’s one of the worst pains I’ve ever felt", "It’s GreenBall, not Greenball.", "Pixels on a screen can make a man surprisingly emotional.\nGoodbye Grand Mapper 3.0!\nYou’ve been… interesting!",
        "So I went to the club last night, something that I’m sure no one except Wonder has done. This is my third time ever going to one, and yknow, I made some observations. \n\nTs is like animal planet bro. Like the club is a glorified Animal Planet documentary about Peacocks mating. So every Friday night, degenerates, thots, and lonely mfs alike gather in one area to listen to normie music butchered by a bad DJ. And, like peacocks, the males surround the females doing some crazy ass dances. Everyone is dressed like a peacock, except if the peacock got oiled up and had each of their feathers skillfully plucked out bc most people were practically naked.\n\nSo the males do their dance to get a female to come by, and then from there they’ll dance together and check compatibility. Yknow sometimes it works well, other times the female is playing games, they both do their lil mating dance together and then they move on unless they RWEALLY like each other. Rinse and repeat. \n\nFor the first hour I’m just chillin there w QBall, I felt very out of place watching the peacocks go. But as I studied more, I realized how this game worked. I realized how to try to be a good peacock. \n\nDance a little bit, pretend to know the lyrics, ask their name, and idk maybe you’ll get far or smth. I kinda did? \n\nTL;DR: Nightclubs are animal planet documentaries, and if you want play you gotta be a good peacock :peacock: (or be a literal 10)", "If I hear “My name is pink and it’s really nice to meet ya. You’re recommended to me by some people.” on ANOTHER insta reel, I’m actually crashing out. I hate it. \n If you, your mom, your hot sister, your dog, your brother, your chopped plastic surgeon friend or your Siib body pillow makes these, tell them to stop. Please it’s making my ears bleed.\n I should become and influencer and start a podcast who’s down?\n PinkPanthress Illegal is a shit song", "Don’t get good at drawing GM balls. It is genuinely one of the most miserable experiences making balls for a season on a deadline as tight as your hot mom’s yoga pants.\nHowever it’s a rite of passage. I lured Drayde and Arux in to get good so that I would be a free man. 12 years a GM cast artist.",
        "This is a personal fuck you to everyone in the New York State government who thought this `Real ID` bullshit was a good idea. Tfym my drivers license isnt valid outside of NY anymore and I need to update it??", "https://cdn.discordapp.com/attachments/1392979488085774356/1399609545583628378/IMG_2115.png?ex=69b98137&is=69b82fb7&hm=8af3e2269317b6aef412fd57348bffe67bf7c85093e4e0c531f102773ce357fa", "Don’t develop feelings for someone.", "They ruin lives. If you come in contact with someone like this AND they like Sanrio shit, run. Run far away. I ran 7 miles at a sub 8 min pace. It’s worth it\nhttps://cdn.discordapp.com/attachments/1392979488085774356/1401035340357304440/IMG_2137.png?ex=69b96b17&is=69b81997&hm=481727b6de89ab9c4131b0d47eb0ed196fad4419c196f010656e0d5aadd91b01", "I LOVE VEGAS. I MAY BE 20, AND CANT DO SHIT BUT TS IS LITTTTT! Bring your children to Vegas please. I played GM3 while in Vegas at the ripe old age of 13. I LOVE LAS VEGAS!!!",
        "If you order a quadruple burger at Heart Attack Grill in Vegas, you WILL get spanked by one of the nurse waitresses. Meh, at least she was bad…", "[insert Green's footpic here that will make you gauge your eyes out]", "Get a good barber. Or stylist if you’re a chick. Seriously. \nI used to *dread* haircuts, because I would lowk get ruined by so many different barbers/friends moms. Fun GreenBall fact, I actually shaved my head completely bald in August 2023 (real ones know why) and I haven’t recovered since! So every haircut I’ve gotten since shaving my head has usually been pretty bad, whether it be the awful barbers at my school, or other arrogant assholes who boast about their ChatGPT generated dad lore claiming they know what they’re doing (fuck you chase bank manager web dev bald guy, I had you twice and you fucked my head up twice). \nBut dude, get yourself a barber that can LISTEN. Holy shit man. My friend once said he wanted an inch off the top, and this DUMBASS BARBER shaved his entire head of hair off (bro didn’t hear a thing). Some of these barbers have the listening skills of underwater orangutans with cocomelon earrape blasting in their headphones while submerged on the titanic. \nSo I recently got a haircut, and I got no barber loyalty because barely any of them have treat my head right, so I’m essentially like a bitchy whore going from guy to guy. But then, I found Nick. \nMy mom recommended Nick to me because she kept demanding that I get a haircut, and I lowk needed one before I go back to university. So I go to nick, and he has amazing listening skills, and is able to actually understand how my hair works and give me a new style that fits it. I like my hair a little longer on the top but I have to have buzzed sides for school, and he kept the length that I liked. He was perfect. He listened, he could talk, he was understanding, Grand Mapper ladies (and Tetno because he’s GAY) you would love him. \nSo yeah. I got a slightly new hairstyle now, and I’m pretty stoked about my new haircut. All because I got a brand new barber. \nStar this message if you think I should do a barber tier list.",
        "There’s not many feelings better than taking a FAT SHIT. Honestly, I feel like we should normalize feeling a sense of pride and accomplishment with the shits we take. I just too a massive one and dude I’m lowk impressed. Kinda giving myself a pat on the back rn.", "If you’re at a bar and there’s a wasted chopped shyt crusty 40 year old woman, and she offers to play thumb of war with you, DON’T do it! \nShe will purposely lose bc she’s stupid and fucked up and drunk, and then take your hand and put her crusty ass lips on it and kiss your hand like you’re a whole ass Disney Princess. \nTL;DR middle aged chopped drunk women are the absolute worst", "Billie Eilish is bad asf", "**TL;DR** If you truly want something, you can’t give up, and for you to experience success it’s helpful to have a reason why to keep going and persevere through everything. Think about what you truly want in life and work towards it. It’s best if you’re obsessed. Be obsessed to chase racks, get your dreams, make that career work, go to that school, or whatever it may be. I believe in y’all :) \n (You can real the full advice here: https://discord.com/channels/1375496972705988628/1392979488085774356/1409308931381268600)",
        "yknow performative males that glaze women for having periods and how hard they are. Well FUCK THAT. Women, you have it easy. Have you ever been a man that has dealt with CHAFING? It is one of the worst feelings in the world (and I’m going through it rn).\nGuys. I think the inventor of periods and chafing is evil…\nKeep Me Safe From the Chafe!\n#KeepMeSafeFromTheChafe", "I have grown Grand Mappers. Those who have stuck with me for a while may remember my first life advice, where I used the Taco Bell drive thru without a car and got laughed at by blonde college chicks. \n\nI am now in that same fateful drive through with my car! Sitting and waiting for a simple order that is taking forever!\n**GreenBall’s Life Advice #52**\nPeople will probably think you’re fat if you take too long at the drive thru, however, it is sometimes the smallest orders (one burrito one taco) that cause giants to crumble. It has been a solid 10 minutes now and there is a massive line behind me.", "whatever the fuck this is ighttps://cdn.discordapp.com/attachments/1392979488085774356/1411937494051852390/IMG_2517.png?ex=69b98783&is=69b83603&hm=6cb93a147b9bb4cca31f8177ad6343218e5f63a4e8a000807f03d4847c765893",
        "All good things must come to an end.\nBecause what makes the good times special is the bad times\nor it’s temporary nature\nThe absence of good makes the good times good", "Anyway, we all know what just happened with Charlie Kirk. Like him or not, I personally didn’t give a fuck ab him, it’s awful how we lost a human life. Same goes to the Ukrainian woman who tragically lost her life some time ago. \nNot a political statement, just like, respect human life. I’d be sad if even my biggest opps died. \nAlso genuinely be careful out there yall. Deadass…", "NEVER bring someone’s relatives or family into something if you hate them. Scummiest thing you can do is go for the innocent or people barely involved", "soft, gooey cookies > hard cookies \n\nobjectively.\nif you like hard cookies you’re like a fucking dog\nyou like a hard ass frisbee in your mouth\nhttps://tenor.com/view/tricks-skills-flip-frisbee-jump-gif-14245216", "Do you remembar?", "FABOOMKO:\nNever let bro cook again.\n(He said chatgpt can make hot ai-generated baddies)\nhttps://cdn.discordapp.com/attachments/1392979488085774356/1415448108900421633/image.png?ex=69b91e06&is=69b7cc86&hm=2e82983e1cc404238bdd44359ec9c4695ec909d3d7c4c391c69adff46ff92ae4",
        "Yes, this is deadass greenball himself typing from fabs phone, I am sleeping on his dorm room floor tonight. But yeah, hope yall have been doing well ig.\n\nYeah, I technically left GM because American won GM30. I made a bet w some lads in a gc about it and if American won and Empirus lost then id leave the server. It's something I frankly needed, especially as I rapidly chase a new phase in life and need more things to fill my time with. \n\nI also didnt like the direction gm in general was going, wasn't as fun and exciting as it was in the ankhor and late siib era. `@Producer` I told yall little shits to make an all newbie 16 player season millions of times but no one listens to daddy anymore.\n\nI also got a lot of aspiration s in life I gotta start working towards, and I need to align my f0cus and mindset on those.\n\nWith that all said, I'll get into the actual life advice.\n\nDude Diwali parties are lit me and fab went to one tn and it was Hella fun. I didnt even know wtf Diwali was until a quick Google search in a cramped apartment blasting Indian music and everyone was drunk. It's so weird to be at a normal college like idk bro this is so nice. But yeah, I love India :flag_in: Go India!\nAlso I am wearing the gm shirt"]; 
    }
    
   	getSilly(){
    const silly = JSON.parse(fs.readFileSync('./silly.json'));
    return silly;
    }
    
    
	getMeme() {
    const memes = JSON.parse(fs.readFileSync('./memes.json'));
    return memes;
}
    
}

module.exports = StringArray;